const garbage = ['tissue', 'bag', 'broom', 'mop','lumber','drywall','insulation','moulding','decking','ceiling tiles','roofing shingles', 'millwood','siding','fencing','concrete cement','ventilation','glass' ,'acrylic','paint','spray paint','paint rollers','paint brushes','primer','tape','glues','cleaning chemicals','chandeliers','ceiling fans','light bulbs','lamps','lamp shades', 'coffee maker',
'blenders & juicers',
'slow cookers',
'multi pots',
'microwaves',
'toasters',
'convection ovens',
'electric grills & skillets',
'fryers',
'glass',
'glass packaging',
'window glass',
'glass shards',
'glass shard',
'wooden decor',
'ceramic decor',
'wood',
'ceramic',
'clay', 
'strollers',
'umbrellas',
'sunglasses',
'infant car seats',
'convertible car seats',
'booster car seats',
'alkaline batteries',
'aa batteries',
'aaa batteries',
'c batteries',
'battery chargers',
'd batteries',
'hearing aid batteries',
'coin',
'button cell batteries',
'toothpaste',
'tooth brush',
'deodorants',
'antiperspirants',
'shaving cream',
'tampons',
'feminine pad',
'incontinence',
'body wash',
'shower gel',
'bar soap',
'bubble bath',
'soak',
'bath bomb',
'bath salt',
'body scrubs',
'exfoliating scrub',
'loofah' ,
'bath accessorie',
'baby bath',
'body lotion',
'body cream',
'body butter',
'body oil',
'body care set',
'fragrance',
'perfume',
'nail polish',
'fingernail clipper',
'nail shaper',
'nail file',
'nail polish remover',
'false nail',
'blush',
'bronzer',
'concealer',
'foundation',
'mascara',
'eyeliner',
'eyeshadow',
'false lashe',
'false hair',
'mouth wash',
'footwash',
'plastic utensil',
'saran wrap',
'plastic wrap',
'aluminum wrap',
'rug',
'balloon',
'streamer',
'loot bag',
'confetti',
'candle',
'disposable plate',
'disposable spoon',
'disposable fork',
'disposable knife',
'firework',
'fireworks plastic wrapper',
'air freshener',
'disinfectant wipe',
'paper cleaning product',
'cat collar',
'air freshener',
'disinfectant wipe',
'paper cleaning product',
'baseball glove',
'shin guard',
'knee guard',
'roller skate',
'hockey skate',
'scooter',
'elbow pad',
'mouthguard',
'boxing glove',
'tennis racquet',
'action figure',
'dolls'];

const rec = ['dresser','bed Frame', 'box Spring','nightstands', 'mattresses', 'mattress topper','futon mattresses', 'mattress covers', 'armoires','cardboard', 'paper', 'cereal box', 'baby crib', 'rocking chair', 'crib mattres', 'changing table','metal table', 'metal chair','wooden table','wooden chair','wooden stool','metal stool','sofa','couche','accent chair','sofa bed','loveseat','recliner', 'stand mixer', 'soda maker', 'vacuum sealer', 'refrigerator','freezer', 'ice maker','washer', 'dryer','ovens & range','dishwasher', 'microwave','stick vacuum',
'refurbished vacuum','vacuum',
'canister vacuum',
'steam mop',
'handvac',
'robot vacuum',
'air conditioner',
'fan',
'napkin',
'speaker',
'speakers',
'desktop speakers',
'heaters',
'humidifiers',
'irons & clothes steamers',
'sewing machines',
'baby food makers',
'baby formula makers',
'bottle sterilizers',
'bottle warmers',
'mandolines & slicers',
'tupperware',
'cutting boards & sharpeners',
'filtered water dispenser',
'winter tires',
'car tires',
'light truck & suv tires',
'performance tires',
'tire rims',
'tire covers',
'small tire',
'wheel accessories',
'tire pressure gauges',
'monitoring systems',
'car stereos',
'backup cameras',
'dash cams',
'automotive speakers',
'satellite radios',
'generators',
'inverters',
'power washers',
'air tools',
'compressors',
'windshield wiper blades',
'brakes & brake parts',
'auto filters',
'windshield wiper blades',
'brakes',
'brake parts',
'bassinets',
'toddler bedding',
'bedding',
'wooden crib',
'changing table',
'rocking chair',
'crib mattresse',
'cotton shirt',
'denim',
'silk',
'textile',
'leather',
'chiffon',
'leather handbag',
'leather wallet',
'aluminum wallet',
'carbon fibre',
'basketball shoes',
'soccer cleat',
'football cleat',
'cleats',
'running shoe',
'boots',
'casual shoe',
'sandals/slide',
'heely',
'skate',
'light up sneaker',
'nike',
'jordan',
'adidas',
'new balance',
'timberland',
'converse',
'vans',
'ugg',
'champion',
'ethika',
'kappa',
'puma',
'reebok',
'under armour',
'suitcases',
'backpacks',
'duffle bags',
'nylon bags',
'messengers & work bags',
'laptops',
'keyboards & mice',
'computer monitors',
'pc gaming',
'printers & supplies',
'hard drives & storage',
'desktop computers',
'wifi router',
'headset & microphones',
'graphics cards',
'cpu / computer processors',
'motherboard',
'computer memory',
'ram',
'computer power supplies',
'apple ipad',
'android tablets',
'windows tablet',
'iphone',
'samsung phone',
'huawei phone',
'ereaders',
'cables',
'dslr cameras',
'mirrorless cameras',
'action cameras & camcorders',
'point & shoot cameras',
'instant cameras',
'lenses',
'action & body-mounted camera accessories',
'tripods, mounts & stabilizers',
'memory cards & card readers',
'camera bags & cases',
'drones',
'drone controller',
'security cameras',
'dash cameras',
'sound bars',
'receivers',
'wireless multi-room speakers',
'home speakers',
'home theatre systems',
'portable bluetooth speakers',
'party speakers',
'apple ipod',
'mp3 players',
'turntables',
'mini stereo systems',
'clock radios',
'earbuds',
'in-ear headphones',
'on-ear headphones',
'over-ear headphones',
'gaming headphones',
'truly wireless headphones',
'playstation 4',
'playstation 5',
'xbox',
'nintendo',
'wii',
'nintendo switch',
'virtual reality',
'smartwatches',
'treadmills',
'elliptical machines',
'rowing machines',
'heart rate monitors',
'blood pressure monitors',
'smart glasses',
'dash cameras',
'backup cameras',
'gps',
'smart speakers',
'smart displays',
'smart speaker accessories',
'bikes & scooters',
'hoverboards',
'binoculars',
'electric shaving machine',
'skin razors',
'bedding sets',
'bed sheets',
'pillows',
'blankets',
'mattress covers & protectors',
'pots & pans',
'silverware',
'wooden utensils',
'tupperware',
'plastic baking tools' ,
'metal baking tools',
'glass baking tools',
'toasters',
'electric grills', 
'blenders',
'coffee makers',
'air fryer',
'microwave',
'air conditioners',
'fans',
'heaters',
'humdifiers',
'metal tools',
'chainsaw',
'lawnmower',
'grass clipper',
'pendants',
'necklaces',
'earrings',
'rings',
'bracelet',
'charm',
'jewellery',
'brooche',
'pin',
'anklet',
'hardcover books',
'softcover books',
'cd',
'blu-ray disc',
'vinyl record',
'stapler',
'hole puncher',
'divider',
'paper cutter',
'paper clips',
'pens',
'pencil',
'crayon',
'marker',
'printer paper',
'notebooks' ,
'notepad',
'file',
'file folder',
'binder',
'calculator',
'plastic geometry set',
'metal geometry set',
'paper decoration',
'greeting card',
'fog machine',
'snow blower',
'ice melter',
'snow shovel',
'snow rakes',
'plastic rake',
'squeegees',
'snow brushes',
'scrapers',
'propane bbq',
'charcoal bbq',
'electric bbq',
'outdoor griddle',
'portable bbq',
'leaf blower',
'cat nail scissor',
'electric collar',
'cat/dog shampoo container',
'pet medicine cardboard packaging',
'skateboards',
'hockey puck',
'basketball net',
'basketball',
'soccer ball',
'baseball',
'volleyball',
'metal baseball bat',
'wooden baseball bat',
'helmets',
'leather punching bag',
'controllers',
'remote control vehicles',
'board games',
'puzzle pieces',
'doll houses',
'magnetic toys',
'wooden blocks',
'learning tablets',
'toy blasters',
'cards',
'train sets',
'paper food wrapper',
'plastic bottle',
'plastic',
'hard plastic',
'cardboard',
'cardboard packaging',
'cardboard box'];

const com = ['apple', 'banana','banana peel',
'fruits',
'vegetables',
'dairy product',
'grain',
'bread',
'paper napkin',
'egg shell',
'coffee filter',
'meat',
];

const hazWaste = ['petrol', 'battery', 'car batterie',
'marine battery',
'motor oil',
'windshield washer fluid',
'transmission', 
'brake',
'steering fluid',
'antifreeze',
'car coolant',
'additive',
'grease', 
'gear oil',
'tire sealant'];


let newItems = []


function categorizer(a) {
    console.log(a)
    let category = ""
    let methodofdisposal = ""
    if (garbage.includes(a) == true) {
        category = 'Your item was classified as Garbage, '
        methodofdisposal = 'Look for any trash cans or mass dumpsters to throw away your item'
        document.getElementById('trashtype').innerHTML = category + methodofdisposal
        console.log(category)
        console.log(methodofdisposal)
    }
    else if (rec.includes(a) == true) {
        category = 'Your item was classified as Recyclable, '
        methodofdisposal = 'Look for Blue bins or a trash can with a recycling symbol on it to throw away these items'
        document.getElementById('trashtype').innerHTML = category + methodofdisposal
    } 
    else if (com.includes(a) == true) {
        category = 'Your item was classified as a compost/organic, '
        methodofdisposal = 'You may use these items as fertilizer in soil or dispose of them in a green compost bin'
        document.getElementById('trashtype').innerHTML = category + methodofdisposal
    } 
    else if (hazWaste.includes(a) == true) {
        category = 'Your item was classified as a Hazardous Waste, '
        methodofdisposal = 'Hazardous Waste is disposed in many different ways, learn more here - https://www.toronto.ca/services-payments/recycling-organics-garbage/household-hazardous-waste/'
        document.getElementById('trashtype').innerHTML = category + methodofdisposal
    }
    else if ((hazWaste.includes(a)&&com.includes(a)&&garbage.includes(a)&&rec.includes(a)) == false){
        category = ''
        methodofdisposal = 'This Item is not available in our database, to submit a request to add it to our database, head to our home page and fill in a short form'
        document.getElementById('trashtype').innerHTML = category + methodofdisposal}
}
